service:
  name: change-machine
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:  
  graphql:    
    handler: handler.graphqlHandler    
    events:      
      - http:          
        method: post
        path: graphql
        cors: true
  playground:
    handler: handler.playgroundHandler
    events:
    - http:
        path: graphql
        method: get
        cors: true
